language: r
cache: packages
r:
- release
warnings_are_errors: true
r_packages:
- rmarkdown

env:
  global:
  - MAKE="make -j 2"
  - GIT_BRANCH="${TRAVIS_BRANCH}"
  - secure: "EC7+Hl+cICWKAdNkjXsVc9gETf8KJoEJDVRodUwLJgP2iWlD5NW2q37qItPTIN40vJWvsTzXfroTZQZmJAuYO445Ri2Lfkdzq94dW2bDrnJX0Zs7lgkNIP/TaWo7QrPGtXNRhRFrJSZgpG6UfWTrsCKGsF43HNIHzXdUYLx9Rh2087kqQhcR3SPQZUXnrAPlr78p2/RIINq9ZkXYuntAjmOc9ZWiIMPl1ePXbbDnlUN7U56Y041JmOYK6YxHyoVVN3Wl9Y5ENiYMk2o2eZv9O4DDWjuDbcmtfSI/U9Si+fmPY3mJat8am6l8Ia9IlieULWp/bgLVNAyY9aAEeQlzS1wMesksCSqj+BC7Ewn1Qxn0nCgIYf45xbAgg+mfrHDuyzi3ZhIM30+3L83z2Q7caWxkfcf+Bb/zsKBjr4kZ4afzBkewqq4AaE4aTBQ+z3GJlBLYULfF9SAhQLs5ECzPtpsphc3Q+1Sr27KKmtYX05UOYMzzDoaqOn8pYlRKpaItvtm2CTQ5WGQqmeVZX0RZ9+CYe+158LUB4fnXFEPyq/wjk8h75jZCTy97Ws4tF+yiv7GZe4w/URkB9/W0NRhSuQRNqbnFPUHjEwFnPNCtpNkoLU8vWrxRCARda11/CalxR+MVmkPcy4wk0tyGvs3Jw5YTSGdx1BQQ4rIgIUkM3mQ="

branches:
  only:
  - main
  - develop
  - "/^release\\/v?[\\d\\.]+$/"

stages:
- name: Check
  if: commit_message != "Re-build README.Rmd"
- name: "Extended checks"
  if: commit_message != "Re-build README.Rmd" AND branch != main AND branch != develop


jobs:
- stage: Check
  after_success:
  - R CMD INSTALL .
  - git pull
  - git checkout ${TRAVIS_BRANCH}
  - Rscript -e 'rmarkdown::render("README.Rmd")'
  - git config --local user.email "ci@travis-ci.com"
  - git config --local user.name "Travis CI"
  - git add README.md || echo "Nothing added"
  - git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
  - git remote add originpush "https://${GITHUB_PAK}@github.com/${TRAVIS_REPO_SLUG}"
  - git push --set-upstream originpush ${TRAVIS_BRANCH} || echo "No changes to push"
- stage: "Extended checks"
  name: R-devel
  r: devel
- stage: "Extended checks"
  name: R-oldrel
  r: oldrel
